"""
File:
core/pipeline/review_pipeline.py

Purpose:
Execute the
code review
pipeline.

Why:

Separates code
review from
generation and
repair.

Allows KAIROS to
evaluate generated
or repaired code
without coupling
review logic to
the CLI manager.

Responsibilities:

- Review generated
  or repaired code.
- Collect review
  findings.
- Return a standard
  pipeline result.

Does NOT:

- Generate code.
- Repair code.
- Validate code.
- Execute code.

Architecture:

CLI Manager
      │
      ▼
Pipeline Executor
      │
      ▼
Review Pipeline
      │
      ├── Reviewer Agent
      └── Pipeline Result
"""

from __future__ import annotations

from core.logging.kairos_logger import (
    KairosLogger
)

from core.pipeline.pipeline_context import (
    PipelineContext
)

from core.pipeline.pipeline_result import (
    PipelineResult
)


class ReviewPipeline:
    """
    Execute the
    code review
    workflow.
    """

    def __init__(
        self,
        reviewer
    ):
        """
        Initialize the
        review pipeline.
        """

        self.logger = (
            KairosLogger(
                "review_pipeline"
            )
        )

        # AI agent responsible
        # for reviewing the
        # generated code.
        self.reviewer = (
            reviewer
        )
    
    # ----------------------------------
    # Execute Pipeline
    # ----------------------------------

    def execute(
        self,
        context: PipelineContext,
        implementation: dict
    ) -> PipelineResult:
        """
        Execute the
        review pipeline.
        """

        self.logger.info(
            "Review Started"
        )

        # Ask the Reviewer
        # Agent to inspect
        # the generated or
        # repaired project.
        review = (
            self.reviewer.review_code(

                implementation,

                context=context.shared_context

            )
        )

        self.logger.success(
            "Review completed"
        )
        
    
        # Return a standardized
        # pipeline result so the
        # Pipeline Executor can
        # process every pipeline
        # identically.
        return PipelineResult.success_result(

            pipeline="review",

            data={

                # Complete review
                # generated by the
                # Reviewer Agent.
                "review":
                    review,

            }

        )
    
    # ----------------------------------
    # Pipeline Name
    # ----------------------------------

    @property  # Read-only property. Access like obj.name instead of obj.name().
    def name(
        self
    ) -> str:
        """
        Return the
        pipeline name.
        """

        return "review"
    
    
    # ----------------------------------
    # Supports Pipeline
    # ----------------------------------

    def supports(
        self,
        pipeline: str
    ) -> bool:
        """
        Check whether this
        pipeline can execute
        the requested task.
        """

        return (
            pipeline ==
            self.name
        )