"""
File:
tests/unit/plugins/
test_documentation_plugin.py

Purpose:
Verify DocumentationPlugin.
"""

from core.plugins.documentation_plugin import (
    DocumentationPlugin
)


def test_plugin_name():
    """
    Verify plugin name.
    """

    plugin = DocumentationPlugin()

    assert (
        plugin.name
        == "DocumentationPlugin"
    )


def test_generate_documentation():
    """
    Verify generation.
    """

    plugin = DocumentationPlugin()

    result = plugin.execute(
        "KAIROS"
    )

    assert (
        "# KAIROS"
        in result
    )


def test_returns_string():
    """
    Verify output type.
    """

    plugin = DocumentationPlugin()

    result = plugin.execute(
        "TestProject"
    )

    assert isinstance(
        result,
        str
    )


def test_contains_kairos_signature():
    """
    Verify signature.
    """

    plugin = DocumentationPlugin()

    result = plugin.execute(
        "Demo"
    )

    assert (
        "Generated by KAIROS."
        in result
    )