"""
File: core/agents/memory_agent.py

Purpose:
Generate KAIROS project
memory documentation.

Why:

Every generated project
should automatically receive:

- architecture.md
- roadmap.md
- project_context.md
- memory.md

Architecture:

ArchitectAgent
      ↓
MemoryAgent
      ↓
Documentation
      ↓
CLIManager
      ↓
.kairos/

Future Versions:

V2:
- Context summarization

V3:
- Knowledge extraction

V4:
- Dependency documentation

V5:
- Auto-updating memory

V6:
- Project evolution tracking

V7:
- Autonomous documentation
"""

from typing import Any

# Base agent functionality.
from core.agents.base_agent import BaseAgent

# Provider manager.
from core.providers.provider_manager import ProviderManager

# Provider registry.
from core.providers.provider_registry import ProviderRegistry


from core.logging.kairos_logger import KairosLogger


class MemoryAgent(BaseAgent):
    """
    KAIROS Memory Agent.

    Responsible for generating
    project documentation.
    """

    def __init__(self):
        """
        Initialize memory agent.
        """

        super().__init__(name="MemoryAgent")

        self.provider_manager = ProviderManager(ProviderRegistry())

        self.provider = "ollama"


        # Memory logger.
        self.logger = KairosLogger(
    "memory"
)

    def _provider_response_text(self, response: Any) -> str:
        """
        Convert provider response to text.

        StructuredOutputParser may return Python objects (dict/list) when the
        model emits valid JSON. Plain text responses remain strings. This method
        normalizes both to a string representation suitable for documentation.
        """

        if response is None:
            return ""

        if isinstance(response, str):
            return response

        if isinstance(response, dict):
            # Try common content keys first.
            for key in (
                "content",
                "text",
                "response",
                "markdown",
                "documentation",
                "file_content",
                "generated_content",
            ):
                value = response.get(key)
                if isinstance(value, str):
                    return value
                if isinstance(value, list):
                    return "\n".join(str(v) for v in value)

            # Fallback: stringify the dict.
            return str(response)

        if isinstance(response, list):
            if all(isinstance(item, str) for item in response):
                return "\n".join(response)
            # List of objects - stringify each.
            return "\n".join(str(item) for item in response)

        return str(response)

    # --------------------------------------------------
    # Generate professional KAIROS memory documents.
    #
    # Files:
    # - architecture.md
    # - roadmap.md
    # - project_context.md
    # - memory.md
    #
    # These files become long-term project memory
    # and context for future agent execution.
    # --------------------------------------------------
    def generate_all(self, architecture: dict) -> dict:
        """
        Generate all KAIROS
        memory files.

        Parameters:
            architecture:
                ArchitectAgent output.

        Returns:
            Generated documentation.
        """

        self.audit_logger.log_event(
            "MEMORY_GENERATED", "Memory documentation generated"
        )

        self.memory.store("latest_architecture", architecture)

        self.logger.info(
    "Memory generation started"
)

        self.logger.debug(
            f"Architecture:\n{architecture}"
        )

        self.logger.info(
       "Generating architecture.md"
)
        architecture_md = self._provider_response_text(
            self.provider_manager.execute(
                task_type="documentation",

                prompt=f"""
                    Generate ONLY markdown.

                    Do not output JSON.
                    Do not output Python dictionaries.
                    Do not output explanations.

                    Create a professional architecture.md file.

                    Required Sections:

                    # Architecture

                    ## Project Overview

                    ## Technology Stack

                    ## Directory Structure

                    ## Entry Point

                    ## Execution Flow

                    ## Future Expansion

                    Write the document as if it were generated by
                    a professional software architect.

                    Architecture:

                    {architecture}
                    """,
            )
        )

        self.logger.info(
    "Generating roadmap.md"
)

        roadmap_md = self._provider_response_text(
            self.provider_manager.execute(
                task_type="documentation",

                prompt=f"""
                    Generate ONLY markdown.

                    Do not output JSON.
                    Do not output Python dictionaries.
                    Do not output explanations.

                    Create a professional roadmap.md file.

                    Required Sections:

                    # Roadmap

                    ## Current Status

                    ## Phase 1

                    ## Phase 2

                    ## Phase 3

                    ## Future Improvements

                    Write the document as if it were generated by
                    a senior technical project manager.

                    Architecture:

                    {architecture}
                    """,
            )
        )

        self.logger.info(
    "Generating project_context.md"
)

        project_context_md = self._provider_response_text(
            self.provider_manager.execute(
                task_type="documentation",

                prompt=f"""
                    Generate ONLY markdown.

                    Do not output JSON.
                    Do not output Python dictionaries.
                    Do not output explanations.

                    Create a professional project_context.md file.

                    Required Sections:

                    # Project Context

                    ## Goal

                    ## Purpose

                    ## Scope

                    ## Constraints

                    ## Success Criteria

                    Write the document as if it were generated by
                    a senior software consultant.

                    Architecture:

                    {architecture}
                    """,
            )
        )

        self.logger.info(
    "Generating memory.md"
)

        memory_md = self._provider_response_text(
            self.provider_manager.execute(
                task_type="documentation",
                prompt=f"""
                    Generate ONLY markdown.

                    Do not output JSON.
                    Do not output Python dictionaries.
                    Do not output explanations.

                    Create a professional memory.md file.

                    Required Sections:

                    # Project Memory

                    ## Project Type

                    ## Entry Point

                    ## Requirements

                    ## Important Decisions

                    ## Future Notes

                    Write the document as if it were generated by
                    a senior software architect.

                    Architecture:

                    {architecture}
                    """,
            )
        )


        self.logger.debug(
            f"architecture.md:\n{architecture_md}"
        )

        self.logger.debug(
            f"roadmap.md:\n{roadmap_md}"
        )

        self.logger.debug(
            f"project_context.md:\n{project_context_md}"
        )

        self.logger.debug(
            f"memory.md:\n{memory_md}"
        )

        self.logger.success(
    "Memory generation completed"
)

        return {
            "status": "generated",
            "memory_files": {
                "architecture.md": architecture_md,
                "roadmap.md": roadmap_md,
                "project_context.md": project_context_md,
                "memory.md": memory_md,
            },
        }